- type: entity
  id: SpawnPointIAA
  parent: SpawnPointJobBase
  name: IAA
  components:
  - type: SpawnPoint
    job_id: IAA
  - type: Sprite
    layers:
      - state: green
      - state: lawyer

- type: jobIcon
  parent: JobIcon
  id: JobIconIAA
  icon:
    sprite: /Textures/Imperial/Interface/Misc/imperial_job_icons.rsi
    state: IAA

- type: job
  id: IAA
  name: job-name-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:RoleTimeRequirement
      role: JobLawyer
      time: 3600 #Imperial role timers
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 7200 #Imperial role timers
  startingGear: IAAGear
  icon: "JobIconIAA"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Service
    - Brig
    - Maintenance
    - Command
    - External
    - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
  components:
    - type: NGAntagTarget  # Imperial NGAntag
  skills:
  - skillBotany
  - skillBaseMed
  - skillBaseConstraction

- type: startingGear
  id: IAAGear
  equipment:
    id: IAAPDA
    ears: ClothingHeadsetIAA

- type: playTimeTracker
  id: JobIAA
