- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  # Imperial NGAntag
  special:
  - !type:AddComponentSpecial
    components:
      - type: NGAntagTarget

- type: startingGear
  id: PsychologistGear
  equipment:
    # jumpsuit: ClothingUniformJumpsuitPsychologist imperial jumpskirt
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
  storage:
    back:
    - RubberStampPsychologist
