- type: entity
  id: BaseAttachmentsGun
  abstract: true
  name: пушка
  description: привет я пушка мной можно стрелять
  components:
  - type: PointLight
    enabled: false
    mask: /Textures/Effects/LightMasks/cone.png
    autoRot: true
    radius: 6
    netsync: true
  - type: WeaponAttachments
